server:
  port: 8082
  servlet:
    context-path: /dev

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplybookingxhotel@gmail.com
    password: Dinhbaodeptrai123.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/hotel_booking_dev"
    username: postgres
    password: 0911600379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sendgrid:
    api-key:
    from-email: noreplybookingxhotel@gmail.com

  data:
    redis:
      host: redis-14597.c291.ap-southeast-2-1.ec2.cloud.redislabs.com
      port: 14597
      password: YnttLGa38uDs29MUZ132smcVDv4Icfzn
      username: default
      ssl:
        enabled: false

cloudinary:
  cloud-name: de2lvbq8f
  api-key: 677342821317714
  api-secret: nYYm8oLiIZx0D4rDVHIkD4yARSA

vnpay:
  tmn-code: DJG7E5P3
  hash-secret: SDD8Z1DSWRM5F9ISCQ3CVGXY4JKTXO2V
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8082/dev/payments/vnpay-return
  ipn-url: http://localhost:8082/dev/payments/vnpay-ipn
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction


app:
  verification-link-base: ${VERIFICATION_LINK_BASE:http://localhost:8082/dev}

springdoc:
  api-docs:
    path: /v3/api-docs
  packages-to-scan: org.baoxdev.hotelbooking_test.controller
  swagger-ui:
    display-request-duration: true
    path: /swagger-ui.html
    groups-order: asc
    operations-sorter: alpha



